# -*- coding: utf-8 -*-
"""BUSCA CONCORRENTE GOOGLE SHOPPING FINALIZADO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vhYufDcRLylbQzzOS76RmuGtKlIBszh
"""

import subprocess
import sys
import time
import shutil
import os
import threading
from queue import Queue

def instalar_dependencias():
    """
    Usa o pip para instalar os pacotes necessários para o script.
    """
    print("--- Verificando e instalando dependências de Python ---")
    pacotes = ['selenium', 'webdriver-manager', 'beautifulsoup4', 'requests']
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", *pacotes], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        print("--- Dependências de Python satisfeitas ---\n")
    except subprocess.CalledProcessError as e:
        print(f"ERRO: Falha ao instalar dependências: {e}")
        sys.exit(1)

def verificar_e_instalar_chrome():
    """Verifica se o Chrome está instalado e, se não estiver, tenta instalá-lo."""
    print("--- Verificando a instalação do Google Chrome ---")
    if shutil.which("google-chrome"):
        print("Google Chrome já está instalado.\n")
        return
    print("AVISO: Google Chrome não encontrado.")
    if sys.platform.startswith('linux'):
        print("Tentando instalar o Google Chrome...")
        try:
            subprocess.check_call(["wget", "-q", "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"])
            subprocess.check_call(["sudo", "apt-get", "update"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            subprocess.check_call(["sudo", "apt-get", "install", "-y", "./google-chrome-stable_current_amd64.deb"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            os.remove("google-chrome-stable_current_amd64.deb")
            print("--- Google Chrome instalado com sucesso! ---\n")
        except (subprocess.CalledProcessError, FileNotFoundError) as e:
            print(f"\n--- ERRO: Falha na instalação automática do Google Chrome: {e}")
            sys.exit(1)
    else:
        print("Por favor, instale o Google Chrome manualmente.")
        sys.exit(1)

# --- INÍCIO DA EXECUÇÃO ---
instalar_dependencias()
verificar_e_instalar_chrome()

# Importações após a instalação
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.chrome.options import Options as ChromeOptions
from webdriver_manager.chrome import ChromeDriverManager
from selenium.common.exceptions import WebDriverException, TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib.parse import urljoin # <-- MUDANÇA: Importado para montar a URL completa

def iniciar_driver():
    """
    Inicializa o driver do Google Chrome com otimizações de performance.
    """
    try:
        chrome_options = ChromeOptions()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument("--window-size=1920,1080")
        chrome_options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")
        chrome_options.add_experimental_option('excludeSwitches', ['enable-logging'])
        chrome_options.add_experimental_option("prefs", {"profile.managed_default_content_settings.images": 2})

        # Oculta logs do webdriver-manager
        os.environ['WDM_LOG_LEVEL'] = '0'

        service = ChromeService(ChromeDriverManager().install(), log_output=subprocess.DEVNULL)
        driver = webdriver.Chrome(service=service, options=chrome_options)
        return driver
    except WebDriverException as e:
        print(f"\nOcorreu um erro ao iniciar o WebDriver do Chrome: {e}")
        return None

def extrair_dados_do_sku(url, sku):
    """
    Usa o Selenium para carregar uma página de busca e extrair os dados de concorrentes.
    """
    print(f"\n--- [INICIANDO BUSCA PARA SKU: {sku}] ---")
    driver = iniciar_driver()
    if not driver:
        print(f"\n[FALHA PARA SKU: {sku}] Não foi possível iniciar um navegador.")
        return []
    try:
        driver.get(url)
        clicks = 0
        while clicks < 3:
            try:
                wait = WebDriverWait(driver, 3)
                more_stores_button = wait.until(EC.element_to_be_clickable((By.XPATH, "//span[contains(text(), 'Mais lojas')]")))
                driver.execute_script("arguments[0].click();", more_stores_button)
                clicks += 1
                time.sleep(1)
            except (TimeoutException, Exception):
                break
        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(1)
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height: break
            last_height = new_height
        html_completo = driver.page_source
    except Exception as e:
        print(f"Ocorreu um erro no navegador para o SKU {sku}: {e}")
        return []
    finally:
        if driver: driver.quit()

    soup = BeautifulSoup(html_completo, 'html.parser')
    ofertas = soup.find_all('div', attrs={'jsname': 'uwagwf'})
    if not ofertas: return []

    dados_extraidos = []

    for oferta in ofertas:
        # --- Início da Modificação ---
        nome_vendedor = preco = link_concorrente = None # <-- MUDANÇA: Adicionado 'link_concorrente'

        tag_nome = oferta.find('div', class_='gUf0b')
        if tag_nome:
            nome_vendedor = tag_nome.get_text(strip=True)

            # <-- MUDANÇA: Bloco para encontrar o link
            tag_link = tag_nome.find_parent('a')
            if tag_link and tag_link.has_attr('href'):
                link_href = tag_link['href']
                # Converte o link (que é relativo, ex: /url?q=...) em um link absoluto
                link_concorrente = urljoin("https://www.google.com/", link_href)

        tag_preco = oferta.find('span', class_='Pgbknd')
        if tag_preco:
            preco = tag_preco.get_text(strip=True)
        else:
            tag_preco_alt = oferta.find('div', class_='JIep9e GBgquf')
            if tag_preco_alt: preco = tag_preco_alt.get_text(strip=True)

        # <-- MUDANÇA: Verifica se os 3 campos foram encontrados
        if nome_vendedor and preco and link_concorrente:
            dados_extraidos.append({
                'vendedor': nome_vendedor,
                'preco': preco,
                'link': link_concorrente # <-- MUDANÇA: Adiciona o link ao resultado
            })
        # --- Fim da Modificação ---

    print(f"--- [FINALIZADO SKU: {sku}] Encontrados {len(dados_extraidos)} concorrentes. ---")
    return dados_extraidos

def worker(q, resultados):
    """Função que será executada por cada thread."""
    while not q.empty():
        sku, url = q.get()
        # Limpa espaços em branco do SKU e da URL
        sku_limpo = sku.strip()
        url_limpa = url.strip()
        if sku_limpo and url_limpa:
            resultados[sku_limpo] = extrair_dados_do_sku(url_limpa, sku_limpo)
        q.task_done()

# --- Execução Principal ---
if __name__ == "__main__":
    start_time = time.time() # Marca o tempo de início da execução

    print("--- Extrator de Concorrentes por SKU ---")

    # Dicionário de produtos para buscar
    produtos_para_buscar = {
       " 250948 " : " https://www.google.com/search?ibp=oshop&q=ALICATE+CRIMPADOR+PRENSA+TERMINAL+0.1+A+2.5MM+BARRIL+ABERTO&prds=catalogid:7608826687185219809,gpcid:11598877188482179447,headlineOfferDocid:16300931587296363865,imageDocid:7493882308667207975,mid:576462860872324804,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 301913 " : " https://www.google.com/search?ibp=oshop&q=ALICATE+CRIMPADOR+PRENSA+TERMINAL+0.5+A+6MM+TERM+TUBULAR&prds=catalogid:8772962661069899532,gpcid:1185672152229034755,headlineOfferDocid:2005856527101559458,imageDocid:3921670759506743975,mid:576462728847391607,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 311109 " : " https://www.google.com/search?ibp=oshop&q=ALINHADOR+DE+CORREIA+LASER+TKBA+21+SKF&prds=catalogid:17074562992878519133,gpcid:12437481685404306412,headlineOfferDocid:14659306486243324287,imageDocid:2882277369840417696,mid:576462863255388305,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 206254 " : " https://www.google.com/search?ibp=oshop&q=BANCADA+ABERTA+1GAV+TAMPO+ACO+1500MM+AZUL+DESMONTADA&prds=catalogid:6296097994523859147,gpcid:2058620089520680199,headlineOfferDocid:12065404010473110502,imageDocid:4354932084546348666,mid:576462850318093077,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 285220 " : " https://www.google.com/search?ibp=oshop&q=BANCADA+ABERTA+2GAV+TAMPO+COMPENSADO+2000MM+AZUL+DESMONTADA&prds=catalogid:15515797229735817554,gpcid:13365356368221373742,headlineOfferDocid:3073684045397657885,imageDocid:2103090705781087214,mid:576462472847168664,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 224372 " : " https://www.google.com/search?ibp=oshop&q=BANCADA+ABERTA+S/GAV+TAMPO+COMPENSADO+40MM+1100X600X852MM+DESMONTADA&prds=catalogid:11246779163546947564,gpcid:523577773040358266,headlineOfferDocid:3831241909273136802,imageDocid:14872606615050778221,mid:576462814671635685,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 204537 " : " https://www.google.com/search?ibp=oshop&q=BANCADA+ABERTA+S/GAV+TAMPO+COMPENSADO+40MM+1100X600X852MM+DESMONTADA&prds=catalogid:9222531628830978408,gpcid:4836363986664348787,headlineOfferDocid:9462116607126858966,imageDocid:1939945684166641434,mid:576462807793146884,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 197171 " : " https://www.google.com/search?ibp=oshop&q=BANCADA+FECHADA+2+PRATELEIRAS+TAMPO+COMPENSADO+2000MM+AZUL&prds=catalogid:12683395950276485387,gpcid:272343973071213287,headlineOfferDocid:4341697551892561079,imageDocid:8712077171315595330,mid:576462840027840913,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 " ,
       " 206258 " : " https://www.google.com/search?ibp=oshop&q=BANCADA+FECHADA+7GAV+TAMPO+ACO+1400X554X865MM+AZUL&prds=catalogid:15377822546279892565,gpcid:8774303636807400565,headlineOfferDocid:4281867390162029232,imageDocid:7829031786062984425,mid:576462764642477107,pvo:25,pvt:hg,rds:&pvorigin=25&hl=pt-BR&gl=br&udm=28&shndl=37&shem=pvflt,shrtsdl&source=sh/x/prdct/hdr/m1/1&utm_source=pvflt,shrtsdl,sh/x/prdct/hdr/m1/1 "
        }

    if not produtos_para_buscar:
        print("\nNenhum produto foi definido na lista. O programa será encerrado.")
    else:
        q = Queue()
        for sku, url in produtos_para_buscar.items():
            q.put((sku, url))

        NUM_THREADS = 3 # Define o número de buscas simultâneas
        resultados_finais = {}
        threads = []

        print(f"\nIniciando a extração para {len(produtos_para_buscar)} produto(s) com {NUM_THREADS} buscas simultâneas...")

        for _ in range(NUM_THREADS):
            t = threading.Thread(target=worker, args=(q, resultados_finais))
            t.start()
            threads.append(t)

        q.join() # Aguarda a fila esvaziar

        for t in threads:
            t.join() # Aguarda todas as threads terminarem

        print("\n\n==================== RELATÓRIO DA EXTRAÇÃO ====================")

        # <-- MUDANÇA: Modificado para ordenar os SKUs na impressão final
        for sku in sorted(resultados_finais.keys()):
            resultados = resultados_finais[sku]
            if resultados:
                for dado in resultados:
                    print(f"\nSku: {sku}")
                    print(f"Nome do concorrente: {dado['vendedor']}")
                    print(f"Valor de venda do concorrente: {dado['preco']}")
                    print(f"Link do concorrente: {dado['link']}") # <-- MUDANÇA: Imprime o link
            else:
                 print(f"\n--- Nenhum concorrente encontrado para o SKU: {sku} ---")

        print("\n\n==================== EXTRAÇÃO FINALIZADA ====================")

    end_time = time.time() # Marca o tempo de fim da execução
    duration = end_time - start_time
    print(f"\nTempo total de execução: {duration:.2f} segundos.")